version: '2'

volumes:
  grafana-storage:

services:
  prometheus:
    image: prom/prometheus:v2.3.2
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
  node-exporter:
    image: prom/node-exporter:v0.16.0
    command: ["--collector.textfile.directory", "/etc/node-exporter/textfile"]
    volumes:
      - ./textfile:/etc/node-exporter/textfile:ro
  grafana:
    image: grafana/grafana:5.2.4
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
    links:
      - prometheus
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=secret" 
